// Single frozen schema contract for HotSpot's user/social/gamification data.
// Better Auth core tables (user, session, account, verification) live in
// ./auth-schema.ts (generated by `@better-auth/cli generate`) and are
// re-exported here so Drizzle and the auth adapter see one schema module.
export * from "./auth-schema";

import {
  pgTable, text, timestamp, integer, doublePrecision,
  uniqueIndex, index, primaryKey, pgEnum,
} from "drizzle-orm/pg-core";
import { user } from "./auth-schema";

// ── Enums ───────────────────────────────────────────────────────────────
export const checkinVerification = pgEnum("checkin_verification", ["honor", "geofence"]);
export const friendshipStatus = pgEnum("friendship_status", ["pending", "accepted"]);

// ── App tables ──────────────────────────────────────────────────────────

/** 1:1 with Better Auth `user`. */
export const profile = pgTable(
  "profile",
  {
    userId: text("user_id")
      .primaryKey()
      .references(() => user.id, { onDelete: "cascade" }),
    username: text("username").notNull(),
    displayName: text("display_name").notNull(),
    avatarUrl: text("avatar_url"),
    bio: text("bio"),
    points: integer("points").notNull().default(0),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("profile_username_idx").on(t.username)],
);

export const favorite = pgTable(
  "favorite",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    barId: text("bar_id").notNull(), // matches data/bars.ts ids; not an FK
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.barId] })],
);

export const checkin = pgTable(
  "checkin",
  {
    id: text("id").primaryKey(), // crypto.randomUUID()
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    barId: text("bar_id").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    lat: doublePrecision("lat"),
    lng: doublePrecision("lng"),
    verification: checkinVerification("verification").notNull().default("honor"),
    // shaped to emit a CountEvent later (see lib/types.ts CountEvent)
    source: text("source").notNull().default("check-in"),
  },
  (t) => [
    index("checkin_user_idx").on(t.userId),
    index("checkin_user_bar_idx").on(t.userId, t.barId),
    index("checkin_created_idx").on(t.createdAt),
  ],
);

export const friendship = pgTable(
  "friendship",
  {
    requesterId: text("requester_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    addresseeId: text("addressee_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    status: friendshipStatus("status").notNull().default("pending"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.requesterId, t.addresseeId] }),
    index("friendship_addressee_idx").on(t.addresseeId),
  ],
);

/** Badge definitions, seeded in Task 9. */
export const badge = pgTable("badge", {
  key: text("key").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull(),
  icon: text("icon").notNull(), // emoji or icon name
  criteria: text("criteria").notNull(), // human-readable; engine logic keyed by `key`
});

export const userBadge = pgTable(
  "user_badge",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    badgeKey: text("badge_key")
      .notNull()
      .references(() => badge.key, { onDelete: "cascade" }),
    earnedAt: timestamp("earned_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.badgeKey] })],
);

/** Append-only. Leaderboards aggregate amount over createdAt windows. */
export const pointsLedger = pgTable(
  "points_ledger",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    checkinId: text("checkin_id"),
    reason: text("reason").notNull(), // e.g. "checkin", "new-bar", "badge:explorer"
    amount: integer("amount").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("points_user_idx").on(t.userId),
    index("points_created_idx").on(t.createdAt),
  ],
);
